// AUTO-GENERATED by sync-opencode-from-cc.py
// Claude Code 正本の hook 方針を OpenCode plugin へ最小変換した派生物。
import { spawnSync } from "node:child_process"
import { existsSync } from "node:fs"

const PROJECT_ROOT = process.cwd()
const RUNTIME_SPEC = {
  "before": {
    "block_main_commit": true,
    "block_destructive_git": true,
    "pre_pr_check_on_git_push": false
  },
  "after": {
    "write_edit": {
      "auto_catalog": false,
      "check_frontmatter": false,
      "validate_skills": false,
      "validate_ssot": false,
      "validate_prompt_ssot": false
    }
  }
}

function parseHookDeny(stdout) {
  if (!stdout) return null
  try {
    const payload = JSON.parse(stdout)
    const hs = payload && payload.hookSpecificOutput
    if (hs && hs.permissionDecision === "deny") {
      return String(hs.permissionDecisionReason || hs.reason || "blocked by Claude-compatible hook")
    }
  } catch (e) {}
  return null
}

function runProcess(command, args = [], {
  cwd = PROJECT_ROOT,
  env = {},
  stdin = "",
  blockOnError = false,
} = {}) {
  const result = spawnSync(command, args, {
    cwd,
    env: { ...process.env, ...env },
    encoding: "utf-8",
    input: stdin,
  })

  if (blockOnError) {
    const deny = parseHookDeny(result.stdout)
    if (deny) throw new Error(deny)
  }

  if (result.status === 0) {
    return
  }

  const message =
    [result.stdout, result.stderr].filter(Boolean).join("\n").trim() ||
    `command failed: ${command} ${args.join(" ")}`
  if (blockOnError) {
    throw new Error(message)
  }
  console.warn(message)
}

function buildHookPayload(command, cwd) {
  return JSON.stringify({
    tool_input: {
      command,
      cwd,
    },
  })
}

function resolveHookScript(name) {
  const candidates = [
    `${PROJECT_ROOT}/.claude/hooks/scripts/${name}`,
    `${PROJECT_ROOT}/hook-library/scripts/${name}`,
  ]
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate
  }
  return candidates[0]
}

function extractPathsFromPatch(patchText) {
  const paths = new Set()
  for (const line of String(patchText || "").split("\n")) {
    const match = line.match(/^\*\*\* (?:Add File|Update File|Delete File): (.+)$/)
    if (match) {
      paths.add(match[1])
    }
  }
  return [...paths]
}

function validatePath(filePath) {
  if (!filePath) return
  const normalizedPath = String(filePath)

  if (RUNTIME_SPEC.after.write_edit.auto_catalog) {
    runProcess("bash", [`${PROJECT_ROOT}/scripts/auto-catalog-trigger.sh`], { cwd: PROJECT_ROOT })
  }

  if (RUNTIME_SPEC.after.write_edit.check_frontmatter && /skills\/.*SKILL\.md$/.test(normalizedPath)) {
    runProcess(
      "python3",
      [`${PROJECT_ROOT}/scripts/check_frontmatter.py`, "--warn", normalizedPath],
      {
        cwd: PROJECT_ROOT,
        env: { CLAUDE_FILE_PATH: normalizedPath },
      },
    )
  }

  if (RUNTIME_SPEC.after.write_edit.validate_skills && /skills\/.*SKILL\.md$/.test(normalizedPath)) {
    runProcess(
      "bash",
      [`${PROJECT_ROOT}/scripts/validate-skills.sh`, "--warn", normalizedPath],
      {
        cwd: PROJECT_ROOT,
        env: { CLAUDE_FILE_PATH: normalizedPath },
      },
    )
  }

  if (
    RUNTIME_SPEC.after.write_edit.validate_ssot &&
    /(DISTRIBUTION\.yaml|project-registry\.yaml|hook-registry\.yaml)$/.test(normalizedPath)
  ) {
    runProcess("bash", [`${PROJECT_ROOT}/scripts/validate-ssot-consistency.sh`], { cwd: PROJECT_ROOT })
  }

  if (RUNTIME_SPEC.after.write_edit.validate_prompt_ssot && /snippet-prompts\/.*\.md$/.test(normalizedPath)) {
    runProcess(
      "bash",
      [`${PROJECT_ROOT}/scripts/validate-prompt-ssot-consistency.sh`, "--warn", normalizedPath],
      {
        cwd: PROJECT_ROOT,
        env: { CLAUDE_FILE_PATH: normalizedPath },
      },
    )
  }
}

export const RuntimeSyncPlugin = async () => {
  return {
    "tool.execute.before": async (input, output) => {
      if (input.tool !== "bash") return

      const command = String(output.args?.command || "")
      const cwd = String(output.args?.cwd || PROJECT_ROOT)

      if (RUNTIME_SPEC.before.block_main_commit) {
        runProcess(
          "bash",
          [resolveHookScript("block-main-commit.sh")],
          {
            cwd: PROJECT_ROOT,
            stdin: buildHookPayload(command, cwd),
            blockOnError: true,
          },
        )
      }

      if (RUNTIME_SPEC.before.block_destructive_git) {
        runProcess(
          "bash",
          [resolveHookScript("block-destructive-git.sh")],
          {
            cwd: PROJECT_ROOT,
            stdin: buildHookPayload(command, cwd),
            blockOnError: true,
          },
        )
      }

      if (RUNTIME_SPEC.before.pre_pr_check_on_git_push && command.includes("git push")) {
        runProcess(
          "bash",
          [`${PROJECT_ROOT}/scripts/pre-pr-check.sh`],
          {
            cwd: PROJECT_ROOT,
            blockOnError: true,
          },
        )
      }
    },

    "tool.execute.after": async (input, output) => {
      if (input.tool === "write" || input.tool === "edit") {
        validatePath(output.args?.filePath || output.args?.path)
        return
      }

      if (input.tool === "apply_patch") {
        for (const filePath of extractPathsFromPatch(output.args?.patchText || output.patchText)) {
          validatePath(filePath)
        }
      }
    },
  }
}
